#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "==============================================================="
echo "       PROJECT SHIVODAYA :: RICHA DTN TRANSPORT MODULE         "
echo "==============================================================="
echo "[+] Running autonomous Contact Graph Routing (CGR) on 100 space nodes..."
echo ""
time "$SCRIPT_DIR/richa"
echo ""
echo "[+] Output Verification:"
echo "    - Trajectory Dispatch File: $SCRIPT_DIR/richa_dispatch_log.txt"
echo "    - Total Trajectory Records: $(wc -l < "$SCRIPT_DIR/richa_dispatch_log.txt") lines"
echo ""
echo "[+] Sample DTN Bundle Custody Dispatches:"
head -n 20 "$SCRIPT_DIR/richa_dispatch_log.txt"
